#!/bin/bash -e

current_dir=`dirname $0`
source $current_dir/metadata
machine_name="$project_name"_dock
docker_build_options="-q"
docker_options="-it"
command=""

while getopts "vac:zh" option
do
  case $option in
    v)
      docker_build_options=""
      ;;
    a)
      docker_options="-t"
      ;;
    c)
      command="$OPTARG"
      ;;
    z)
      CRAILS_DOCKER_DISABLE_AUTOMATIC_UPDATE="yes"
      ;;
    h)
      echo "Usage: $0 [OPTIONS]"
      echo "  -v    	Verbose docker build (quiet by default)"
      echo "  -a    	Disable interactive mode. This option must be set when the command isn't launched from an interactive shell"
      echo "  -c [CMD] 	Will run 'CMD' instead of opening a shell"
      echo "  -z    	Disable automatic update of crails"
      exit 0
      ;;
  esac
done

if [[ -z $CRAILS_DOCKER_DISABLE_AUTOMATIC_UPDATE ]] ; then
  $current_dir/dependencies/set-crails-version.sh
fi

set -x

docker build $docker_build_options -t "$machine_name" docker

docker run --net=host $docker_options --rm \
  -v "`pwd`:/opt/webapp" \
  "$machine_name" bash $command
